In [18]:
!pip install numpy scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [19]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [20]:
x = [ [10], [15], [9], [18], [3] ]

In [21]:
y = [ 2, 3, 1.5, 3.5, 0.5 ]

In [22]:
x,y = np.array(x), np.array(y)

In [23]:
x

array([[10],
       [15],
       [ 9],
       [18],
       [ 3]])

In [24]:
y

array([2. , 3. , 1.5, 3.5, 0.5])

In [25]:
model = LinearRegression()

model.fit(x,y)

model

LinearRegression()

In [26]:
model.intercept_

-0.15746268656716378

In [27]:
model.coef_

array([0.20522388])

In [28]:
x

array([[10],
       [15],
       [ 9],
       [18],
       [ 3]])

In [29]:
model.predict(x)

array([1.89477612, 2.92089552, 1.68955224, 3.53656716, 0.45820896])

In [30]:
y

array([2. , 3. , 1.5, 3.5, 0.5])

In [31]:
model.score(x,y)

0.990115213406651

In [32]:
x_test = [ [14], [7], [2] ]
y_test = [ 3  ,  2,   1]

In [33]:
x_test, y_test = np.array(x_test), np.array(y_test)

In [34]:
model.score(x_test, y_test)

0.42071786589440885