In [9]:
!pip install numpy scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [10]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [11]:
x = [ [10], [15], [9], [18], [3] ]

In [12]:
y = [ 1, 1, 0, 1, 0 ]

In [13]:
x,y = np.array(x), np.array(y)

In [14]:
x

array([[10],
       [15],
       [ 9],
       [18],
       [ 3]])

In [15]:
y

array([1, 1, 0, 1, 0])

In [16]:
model = LogisticRegression()

model.fit(x,y)

model

LogisticRegression()

In [17]:
y_pred = model.predict(x)

y_pred

array([1, 1, 0, 1, 0])

In [18]:
y

array([1, 1, 0, 1, 0])

In [19]:
print("Train Accuracy of Logistic Regression model is:", accuracy_score(y, y_pred)*100)

Train Accuracy of Logistic Regression model is: 100.0


In [20]:
x_test = [ [14], [7], [2] ]
y_test = [ 1  ,  0,   0]

In [21]:
x_test, y_test = np.array(x_test), np.array(y_test)

In [22]:
y_pred = model.predict(x_test)

In [23]:
print("Test Accuracy of Logistic Regression model is:", accuracy_score(y_test, y_pred)*100)

Test Accuracy of Logistic Regression model is: 100.0
